# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190426_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=256)),
                ('level', models.IntegerField(choices=[(0, 'Info'), (1, 'Warn'), (2, 'Critical')], default=0)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Point')),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
                'ordering': ['-c_time'],
            },
        ),
    ]
